# Generated by Django 2.1.3 on 2019-03-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='isues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thes', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(1, 'To DO'), (2, 'In Progress'), (3, 'Code Review'), (4, 'Redo'), (5, 'Test'), (6, 'Done')], default=1, max_length=20)),
                ('kind', models.CharField(choices=[(1, 'Story'), (2, 'Task'), (3, 'Bug')], default=3, max_length=20)),
            ],
        ),
    ]
