# Generated by Django 2.1.3 on 2019-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20190305_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Story'), (2, 'Task'), (3, 'Bug')], default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Code Review'), (4, 'Redo'), (5, 'Test'), (6, 'Done')], default=1, max_length=20),
        ),
    ]
