# Generated by Django 2.1.3 on 2019-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20190305_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
