# Generated by Django 2.1.3 on 2019-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_auto_20190305_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Story'), (2, 'Task'), (3, 'Bug')], default=3),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Code Review'), (4, 'Redo'), (5, 'Test'), (6, 'Done')], default=1),
        ),
    ]
