# Generated by Django 2.1.4 on 2019-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_auto_20190306_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='thesnr',
            field=models.CharField(default='THES-', max_length=200),
        ),
    ]
