# Generated by Django 2.1.4 on 2019-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_auto_20190306_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='sprint',
            field=models.IntegerField(default=5),
        ),
    ]
