# Generated by Django 2.1.4 on 2019-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0009_auto_20190306_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Story'), (2, 'Task'), (3, 'Bug'), (4, 'Sub-Task')], default=3),
        ),
    ]
