# Generated by Django 2.1.4 on 2019-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_auto_20190306_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very Hight'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Lowest')], default=3),
        ),
    ]
