# Generated by Django 2.1.4 on 2019-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0011_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='points',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='issue',
            name='thesnr',
            field=models.CharField(default='THES-', max_length=12),
        ),
    ]
