# Generated by Django 2.1.4 on 2019-03-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0012_auto_20190307_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='points',
            new_name='storypoints',
        ),
    ]
